language: node_js
node_js:
  - "7"
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database pg_extra_test;' -U postgres
  - psql -d pg_extra_test -c 'create table bars (n int not null);' -U postgres
  - psql -d pg_extra_test -c 'insert into bars (n) values (1), (2), (3);' -U postgres
